
=== Domoticz -> Home Assistant

--------
--------


== Une maison manuelle

* actions manuelles répétitives
* oubli des actions

//* on répète tous beaucoup de choses
//* et si on pouvait gagner du temps en en automatisant certaines ?

[.cue]
****
Une des premières chose que j'ai fait quand j'ai cherché à automatiser ma maison a été de lister les points manuels
Ouvrir / fermer les volets roulants: c'est bien mais ca prend quand même pas mal de temps, même s'ils sont électriques.
Gérer la température des pièces: Quand on est parent, on se préoccupe un peu de la température des pièces et de savoir si on doit mettre une couverture supplémentaire à son petit.
Savoir quand une porte / fenêtre est restée ouverte, on aère et parfois on oublie de fermer
Ouvrir la porte du garage
Mettre la VMC en double vitesse quand l'humidité est trop importante dans les pièces d'eau
Et le truc le plus important, ne pas oublier de sortir le linge de la machine à laver pour le transférer dans le sèche-linge. 
Avec des enfants, c'est toujours pratique de ne pas être en rade de bavoirs...
****

== Pourquoi automatiser ?

* parce qu'on est des geeks ?
* pour gagner du temps
* pour se *simplifier* la vie

== Un peu de technique

. *433Mhz*
. Zwave
. Zigbee
. Wifi

[.cue]
****
Avant de pouvoir automatiser et parler de ce qu'on peut faire il faut quand même s'intéresser un peu à la technique.
Globalement, il n'y a que quelques protocoles utilisés dans les solutions grand publics, mais peu sont réellement interconnectables.
****

== 433Mhz

* bon marché
* portée moyenne
* aucune sécurité
* pas de retour d'état

[.cue]
****
Le principal avantage est le coût. Un lot de 3 prises télécommandées s'achète autour de 50€ dans tous les magasins de bricolages (même celui qui vendait des livres à la base...).
On a quelque chose de facile à mettre en place, mais qui ne présente pas de sécurité en contre partie. 
Par exemple, je capte parfaitement le detecteur de mouvement de la cour situé à côté de ma maison, je sais donc quand la lumière se déclenche, complétement inutile...
Le principal défaut est le manque de retour d'état. En fonction du type d'action, on peut être prêt à faire le sacrifice. 
Par exemple un capteur de température comme celui-ci emet l'info toute les 30 secondes, c'est pas grave de rater une salve, c'est plus embêtant de ne pas savoir si une lampe est éteinte ou allumée en revanche. 
****

== 433Mhz 

Exemples:
 
 * capteur de température
 * détecteur de mouvements
 * capteur d'ouverture
 * volets

[.cue]
****
Chez Somfy, le 433Mhz est utilisé, mais c'est en fait un peu sécurisé, il y a un pseudo rolling code qui permet l'appairement.
C'est pas ce qu'il y a de mieux, mais entre pirater un rolling code ou forcer un volet roulant, je ne sais pas ce qui est le plus difficile...
**** 

== 433MHz

Analogie naze, c'est comme de l'UDP, fire and forget
//not convinced by this one


== Un peu de technique

. _433Mhz_
. *Zwave*
. Zigbee
. Wifi

== ZWave

* 868.42 MHz
* prix honnêtes
* portée moyenne
* sécurité forte
* réseau maillé
* avec retour d'état

== ZWave

Exemples:
 
 * capteur de température
 * détecteur de mouvements
 * capteur d'ouverture
 * volets

== Un peu de technique

. _433Mhz_
. _Zwave_
. *Zigbee*
. Wifi

== Zigbee

* 868.42 MHz
* maillé
* sécurisé
* portée moyenne
* open source
* plein d'implémentations ± compatibles

== Zigbee

Exemples:

 * Philips Hue
 * IKEA Tradfri
 * Osram Lightify


== Un peu de technique

. _433Mhz_
. _Zwave_
. _Zigbee_
. *Wifi*


== Wifi

* 2.4GHz / 5GHz
* IP

[.cue]
****
donc une IP par device connecté, nos réseaux de classe C peuvent avoir mal. Est ce que c'est rassurant d'avoir plein de devices connectés sur son réseau IP (pas sans filtrage a mon avis)
****

== Wifi

Exemples:

 * ampoules
 * caméras
 * sonnette

[.cue]
****
Après toute la partie hardware, on peut commencer à s'intéresser au software. 
il existe plusieurs solutions, soit on adhère au lock-in constructeur et on prend une box toute faite (Fibaro, Somfy), sans savoir quelles données sortent de chez nous.
****

== Mise en place

.technos
.besoins
.solution

== Mode dégradé

[.cue]
****
Bien qu'on ait souvent notre Smartphone en main ou pas loin, il n'est pas toujours rapide de l'utiliser.
S’il faut lire un manuel pour allumer la lumière du salon, on a un problème.
Il faut donc bien penser à un mode sans smartphone, sans internet et sans box domotique accessible.
****

== Solutions logicielles

* user friendly
//TODO find out a domoticz screencap
* léger
* maintenu

[.cue]
****
Dans les critères de choix il fallait trouver une solution sympa et utilisable par toute la famille.
J'ai opté pour la solution conseillé par des amis, bon pas vraiment user friendly, mais c'est un projet maintenu et qui supporte pas mal de choses
****

== Solutions logicielles

* openhab
* Jeedom
* Domoticz
* Home assistant

[.cue]
****
Il y a des solutions open source, gratuites ou non.
Jeedom a par exemple tout un jeu de plugin, certains sont payants
****

== Migration de solution

[.cue]
****
J'étais dans une situation où j’avais besoin d’être en version instable (master quoi) de domoticz : xiaomi tout nouvellement supporté, changement dans Harmony … 
Du coup j'ai joué un peu et * faute de build automatique d'image Docker de master, je l'ai mis en place (et il y a des trucs marrant non documentés dans hub.docker.com pour trigger des builds cf repo github)
C'était pas hyper confortable ni sécurisant, j'ai donc repris mes investigations pour trouver une alternative. Avec un peu plus de maturité sur mes besoins, j'ai essayé des solutions plus actives, avec plus de composants supportés et en bonus, un gui sympa. Ce qui m'a amené à retester et adopter Home assistant. 
Ceci étant dit, mon build automatique est toujours vivant et est une image très utilisée (100k pull…)
****

== C'est parti pour la migration

[.cue]
****
Qu'est ce que je perd :

* Historique des éléments (températures, hygrométrie, temps d'utilisation)
* Une interface simple côté administration
* Un logiciel éprouvé
* Des automatisations

Qu'est ce que je gagne :
* Je n’utilise plus master
* Le support de plus de composants
* Un GUI sympa
* La configuration dans des fichiers à plat (bon c'est quand même du yml)
****

== Problème zwave

[.cue]
****
Changement du Synology vers un pi
Changement de domoticz vers Home assistant en passant par jeedom
Découverte de difficulté sur la portée réseau
Firmware fibaro bancal
****

== Lenteurs

[.cue]
****
Toutes les technologies ne permettent pas de faire autrement que du polling
Réseau domestique bien occupé
Routeur performant conseillé (pb Samsung ssid, blocage de l’outbound, segment réseau à part)
****

== Cas d’utilisation

[.cue]
****
Allumage des lumières lorsque je sors de mon garage
Alerte de porte restée ouverte (garage / baie vitrée / entrée…)
Extinction globale des éléments du salon (scenario dodo)
Activation du mode absent automatique (alerte d’ouverture de porte, extinction musique / lumières…)
Alerte de fin de lessive (pour ne pas oublier de la sortir et de la transférer dans le sèche linge)
****

== Automatiser mais pas trop

[.cue]
****
Un des trucs marrants quand on tente d'automatiser c'est qu'on a tendance à oublier pas mal de conditions.
Exemple : allumer toutes les lampes lorsqu'une est allumée dans la pièce, j’en éteins une manuellement, oups elle se rallume : il faut prendre en compte l’historique récent.
Par contre on peut assez facilement envisager de passer les lumières du salon en mode “cinéma” lorsque la télé est allumée et qu'on est après le coucher du soleil. Par contre attention de ne pas allumer les lumières si elles ne l’étaient pas (ou être conscient que ça peut arriver).
J’éteins une lampe d’un scenario, il ne faut pas qu’elle se rallume sur l’action d’un scenario (effet mémoire temporaire)
****

== En vrac des technologies utilisées

* RfxTrx
* ZWave 
* Ikea Trafri
* Philips Hue
* Xiaomi Home
>>> * Dash button
* Netatmo weather
* Logitech Harmony
* Spotify connect
* Yamaha
* Samsung TV | Wash
* Dialogflow
* Home-Assistant
* Google home
* Facebook Messenger
* Slack
* Apple Homekit
>>>* Amazon Dash button
* Google Chromecast
* Synology Surveillance Station
* Synology DSM
>>>* Somfy RTS
* AsusWRT
* IFTTT
>>>> * Syncthing

== Démo Time

[.cue]
****
Montrer le démarrage de Hass
La simplicité d'installation via pip
Montrer le fichier de configuration et booter le gui avec du zwave et du rfxtrx (prise commandée, température), zwave avec prise fibaro, capteur de porte.

Écrire une automatisation, TODO

Faire un exemple dialogflow (vérifier ngrok, reverse tunnel, whatever), et slack
****

[.bibliography]

* https://www.youtube.com/watch?v=OZyzfnZVCCk Black Mirror Clip from White Christmas Episode
* https://www.youtube.com/watch?v=sXH2K2ZlrjQ Iron Man's Alarm Clock(scene from movie)
